### ISSUE TITLE
Allow captions to show in VOD

### ISSUE THREAD

**Issue by jmytch** [talk2MeGooseman/Stream-Closed-Captioner#11]
I get frustrated when it comes to streamers being offline every time I go to their stream but look back on their vod (past broadcast) on twitch and find it that captions is not displaying in the vod even though the streamer has your closed captioning extension enabled.

Would like to request to please allow captions on vod if possible?

**Comment by talk2MeGooseman** [comment]
Hey @jmytch, sorry for delayed response. Unfortunately one of the downsides to using closed captioning as a Twitch extension is that it wont display on the VODs. There is no work around for this right now but in the future there I might add the ability to embed closed captioning like webcaptioner.com . A great alternative to the extension is webcaptioner.com so I recommend asking them to use that if watching VODs with out closed captioning is a feature you would like since it is added as a source to their streaming software.
