### ISSUE TITLE
Viewer side - uncensored profanity?

### ISSUE THREAD

**Issue by jmytch** [talk2MeGooseman/Stream-Closed-Captioner#50]
Upon watching streamers when they are raging on their stream as they play, it shows F******, rather then censoring the profanity, maybe allow the viewers to toggle Profanity On/Off via CC settings menu if they wish to adjust the profanity. Rather than the broadcaster setting them to disabled which is unfair as others would hear what they are being said via voice.

I know the CC settings menu is getting added up alot and that you want to do minimal as possible. I have not seen any other CC extension out there that allows the viewers to toggle what they want where your ones does.

**Comment by talk2MeGooseman** [comment]
Hey thanks for filing an issue. Unforunetly profanity censoring is something that I cannot turn off. Its auto-enabled when using the free Speech-to-Text through Chrome and no way to control turning it off. Believe me I looked into this because others didnt want to be censored lol. Only way around this is to use a paid for service it seems 😢😢😢😢😢

As a side note, there is some server side profanity blocking but thats only censoring I do is for hate words and some really bad words that you dont want the CC think you said.
