### ISSUE TITLE
Brave Browser

### ISSUE THREAD

**Issue by jmytch** [talk2MeGooseman/Stream-Closed-Captioner#54]
**Describe the bug**
When clicking CC menu to selects decrease lines, it doesn't save the last remembered selected options? Works fine on Chrome, but not Brave browser that are using Chromium. Maybe look into Chromium as well to support it until they reset/clear cookies. 

**To Reproduce**
N/A

**Expected behavior**
To save last remember selected options like Google Chrome.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Brave
 - Version [e.g. 22]Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by talk2MeGooseman** [comment]
Thanks, @jmytch for filing this issue. After getting around to looking at why Brave LocalStorage of your settings isn't working I found out that its a security feature of Brave itself. In order to allow the extension to have access to the LocalStorage then you will need to explicitly allow it in the settings.

In order to whitelist the extension so that is can save your setting to LocalStorage do the following:
- Go to: Setting->Additional Settings->Privacy and Security->Site Settings->Cookies
- In the "Allow" section add: https://h1ekceo16erc49snp0sine3k9ccbh9.ext-twitch.tv

The above URL is only for the Stream CC extension so that you're not allowing another extension able to use your LocalStorage.

Cheers!
